name: test_flutter
on: [push, pull_request]
jobs:
  test_flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter test  # --coverage
      #- uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    file: coverage/lcov.info
